const ERROR_CODE_BAD_REQUEST = 400;
const ERROR_CODE_BAD_LOGIN_OR_PASS = 401;
const ERROR_CODE_BAD_AUTH = 403;
const ERROR_CODE_NOT_FOUND = 404;
const ERROR_CODE_INTERNAL = 500;
const SEKRET_KEY = 'some-secret-key';

module.exports = {
  ERROR_CODE_BAD_REQUEST,
  ERROR_CODE_BAD_LOGIN_OR_PASS,
  ERROR_CODE_NOT_FOUND,
  ERROR_CODE_INTERNAL,
  ERROR_CODE_BAD_AUTH,
  SEKRET_KEY,
};
